routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $threads=App\Thread::paginate(15);
    return view('welcome',compact('threads'));
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('/thread', 'ThreadController');

Route::post('thread/mark-as-solution','ThreadController@markAsSolution')->name('markAsSolution');

Route::resource('comment','CommentController',['only'=>['update','destroy']]);

Route::post('comment/create/{thread}','CommentController@addThreadComment')->name('threadcomment.store');

Route::post('reply/create/{comment}','CommentController@addReplyComment')->name('replycomment.store');

app/Thread.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    use CommentableTrait;
    protected $fillable=['subject','type','thread','user_id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Thread;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;


class ThreadController extends Controller
{
    function __construct()
    {
        return $this->middleware('auth')->except('index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $threads= Thread::paginate(15);
        return view('thread.index', compact('threads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('thread.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate
        $this->validate($request,[
            'subject'=>'required|min:10',
            'type'=>'required',
            'thread'=>'required|min:20'
        ]);

        //store
        auth()->user()->threads()->create($request->all());

        //redirect
        return back()->withMessage('Thread Created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function show(Thread $thread)
    {
        return view('thread.single', compact('thread'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function edit(Thread $thread)
    {
        return view('thread.edit',compact('thread'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Thread $thread)
    {
        if(auth()->user()->id !== $thread->user_id){
            abort(401,"Unauthorized");
        }

        //validate
        $this->validate($request,[
            'subject'=>'required|min:10',
            'type'=>'required',
            'thread'=>'required|min:20'
        ]);

        $thread->update($request->all());

        return redirect()->route('thread.show',$thread->id)->withMessage('Thread Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function destroy(Thread $thread)
    {
        if(auth()->user()->id !== $thread->user_id){
            abort(401,"Unauthorized");
        }
        $thread->delete();
        return redirect()->route('thread.index')->withMessage("Thread Deleted!");
    }

    public function markAsSolution()
    {
        $solutionId=Input::get('solutionId');
        $threadId=Input::get('threadId');

        $thread=Thread::find($threadId);
        $thread->solution=$solutionId;
        if($thread->save()){
            /*if(request()->ajax()){
                return response()->json(['status'=>'success','message'=>'marked as solution']);
            }*/
            return back()->withMessage('Marked as solution');
        }

    }
}

resources/views/thread/partials/comment-form.blade.php
<div class="comment-form">

    <form action="{{route('threadcomment.store',$thread->id)}}" method="post" role="form">
        {{csrf_field()}}
        <legend>Create comment</legend>

        <div class="form-group">
            <input type="text" class="form-control" name="body" id="" placeholder="Input...">
        </div>


        <button type="submit" class="btn btn-primary">Comment</button>
    </form>

</div>

resources/views/thread/partials/comment-list.blade.php
<h5>{{$comment->body}}</h5>
@if(!empty($thread->solution))
    @if($thread->solution == $comment->id)
        <button class="btn btn-success pull-right">Solution</button>
    @endif

@else

    <form action="{{route('markAsSolution')}}" method="post">}}
        {{csrf_field()}}
        <input type="hidden" name="threadId" value="{{$thread->id}}">
        <input type="hidden" name="solutionId" value="{{$comment->id}}">
        <input type="submit" class="btn btn-success pull-right" id="{{$comment->id}}" value="Mark As Solution">
    </form>
{{--@can('update',$thread)
    <div  class="btn btn-success pull-right" onclick="markAsSolution('{{$thread->id}}','{{$comment->id}}',this)">Mark as solution</div>
@endcan--}}
@endif

<lead>{{$comment->user->name}}</lead>

<div class="actions">
    {{--<a href="{{route('thread.edit',$thread->id)}}" class="btn btn-info btn-xs">Edit</a>--}}

    <a class="btn btn-primary btn-xs" data-toggle="modal" href="#{{$comment->id}}">Edit</a>
    <div class="modal fade" id="{{$comment->id}}">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
                    </button>
                    <h4 class="modal-title">Modal Title</h4>
                </div>
                <div class="modal-body">
                    <div class="comment-form">
                        <form action="{{route('comment.update',$comment->id)}}" method="post" role="form">
                            {{csrf_field()}}
                            {{method_field('put')}}
                            <legend>Edit comment</legend>

                            <div class="form-group">
                                <input type="text" class="form-control" name="body" id="" value="{{$comment->body}}">
                            </div>

                            <button type="submit" class="btn btn-primary">Comment</button>
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Save changed</button>
                </div>
            </div>
        </div>
    </div>

    <form class="inline-it" action="{{route('comment.destroy',$comment->id)}}" method="POST">
        {{csrf_field()}}
        {{method_field('DELETE')}}
        <input class="btn btn-xs btn-danger" type="submit" value="Delete">
    </form>
</div>

@section('js')
        <script>
            function markAsSolution(threadId, solutionId) {
                    $.post('{{route('markAsSolution')}}', {solutionId: solutionId, threadId: threadId}, function (data) {
                            console.log('success');
                        });
                }
        </script>

    @endsectio

resources/views/thread/partials/reply-list.blade.php
<div class="small well info-text reply-list" style="margin-left: 35px;">
    <h5>{{$reply->body}}</h5>
    <lead> By {{$reply->user->name}}</lead>

    <div class="actions">
        {{--<a href="{{route('thread.edit',$thread->id)}}" class="btn btn-info btn-xs">Edit</a>--}}

        <a class="btn btn-primary btn-xs" data-toggle="modal" href="#{{$reply->id}}">Edit</a>
        <div class="modal fade" id="{{$reply->id}}">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
                        </button>
                        <h4 class="modal-title">Modal Title</h4>
                    </div>
                    <div class="modal-body">
                        <div class="comment-form">
                            <form action="{{route('comment.update',$reply->id)}}" method="post" role="form">
                                {{csrf_field()}}
                                {{method_field('put')}}
                                <legend>Edit reply</legend>

                                <div class="form-group">
                                    <input type="text" class="form-control" name="body" id="" value="{{$reply->body}}">
                                </div>

                                <button type="submit" class="btn btn-primary">Reply</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <form class="inline-it" action="{{route('comment.destroy',$reply->id)}}" method="POST">
            {{csrf_field()}}
            {{method_field('DELETE')}}
            <input class="btn btn-xs btn-danger" type="submit" value="Delete">
        </form>
    </div>

</div>

resources/views/thread/partials/thread-list.blade.php
<div class="list-group">
    @forelse($threads as $thread)

        <a href="{{route('thread.show', $thread->id)}}" class="list-group-item">
            <h4 class="list-group-item-heading">{{$thread->subject}}</h4>
            <p class="list-group-item-text">{{str_limit($thread->thread,100) }}</p>
        </a>
    @empty
        <h5>No threads</h5>

    @endforelse
</div>