routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $threads=App\Thread::paginate(15);
    return view('welcome',compact('threads'));
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('/thread', 'ThreadController');

Route::post('thread/mark-as-solution','ThreadController@markAsSolution')->name('markAsSolution');

Route::resource('comment','CommentController',['only'=>['update','destroy']]);

Route::post('comment/create/{thread}','CommentController@addThreadComment')->name('threadcomment.store');

Route::post('reply/create/{comment}','CommentController@addReplyComment')->name('replycomment.store');

app/Thread.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    use CommentableTrait;
    protected $fillable=['subject','type','thread','user_id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Thread;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;


class ThreadController extends Controller
{
    function __construct()
    {
        return $this->middleware('auth')->except('index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $threads= Thread::paginate(15);
        return view('thread.index', compact('threads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('thread.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate
        $this->validate($request,[
            'subject'=>'required|min:10',
            'type'=>'required',
            'thread'=>'required|min:20'
        ]);

        //store
        auth()->user()->threads()->create($request->all());

        //redirect
        return back()->withMessage('Thread Created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function show(Thread $thread)
    {
        return view('thread.single', compact('thread'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function edit(Thread $thread)
    {
        return view('thread.edit',compact('thread'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Thread $thread)
    {
        if(auth()->user()->id !== $thread->user_id){
            abort(401,"Unauthorized");
        }

        //validate
        $this->validate($request,[
            'subject'=>'required|min:10',
            'type'=>'required',
            'thread'=>'required|min:20'
        ]);

        $thread->update($request->all());

        return redirect()->route('thread.show',$thread->id)->withMessage('Thread Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function destroy(Thread $thread)
    {
        if(auth()->user()->id !== $thread->user_id){
            abort(401,"Unauthorized");
        }
        $thread->delete();
        return redirect()->route('thread.index')->withMessage("Thread Deleted!");
    }

    public function markAsSolution()
    {
        $solutionId=Input::get('solutionId');
        $threadId=Input::get('threadId');

        $thread=Thread::find($threadId);
        $thread->solution=$solutionId;
        if($thread->save()){
            /*if(request()->ajax()){
                return response()->json(['status'=>'success','message'=>'marked as solution']);
            }*/
            return back()->withMessage('Marked as solution');
        }

    }
}

resources/views/thread/create.blade.php
@extends('layouts.front')

@section('heading', "Create Thread")

@section('content')


    <div class="row">
        <div class="well">
            <form class="form-group" action="{{route('thread.store')}}" method="post" role="form"
                  id="create-thread-form">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="subject"><strong>Subject</strong></label>
                    <input type="text" class="form-control" name="subject" id="" placeholder="Input..." value="{{old('subject')}}">
                </div>

                <div class="form-group">
                    <label for="type"><strong>Type</strong></label>
                    <input type="text" class="form-control" name="type" id="" placeholder="Input..." value="{{old('type')}}">
                </div>

                <div class="form-group">
                    <label for="thread"><strong>Thread</strong></label>
                    <textarea class="form-control" name="thread" id="" placeholder="Input...">{{old('thread')}}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

@endsection

resources/views/thread/edit.blade.php
@extends('layouts.front')

@section('heading', "Create Thread")

@section('content')

    @include('layouts.partials.error')

    @include('layouts.partials.success')

    <div class="row">
        <div class="well">
            <form class="form-group" action="{{route('thread.update', $thread->id)}}" method="post" role="form"
                  id="create-thread-form">
                {{csrf_field()}}
                {{method_field('put')}}

                <div class="form-group">
                    <label for="subject"><strong>Subject</strong></label>
                    <input type="text" class="form-control" name="subject" id="" placeholder="Input..." value="{{$thread->subject}}">
                </div>

                <div class="form-group">
                    <label for="type"><strong>Type</strong></label>
                    <input type="text" class="form-control" name="type" id="" placeholder="Input..." value="{{$thread->type}}">
                </div>

                <div class="form-group">
                    <label for="thread"><strong>Thread</strong></label>
                    <textarea class="form-control" name="thread" id="" placeholder="Input..."> {{$thread->thread}} </textarea>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

@endsection

resources/views/thread/index.blade.php
@extends('layouts.front')

@section('heading')

    <a href="{{route('thread.create')}}" class="btn btn-primary pull-right">Create Thread</a> <br>

@endsection

@section('content')

@include('thread.partials.thread-list')

@endsection

resources/views/thread/single.blade.php
@extends('layouts.front')

@section('content')
    <div class="content-wrap well">

        <h4>{{$thread->subject}}</h4>
        <hr>

        <div class="thread-details">
            {!! \Michelf\Markdown::defaultTransform($thread->thread) !!}
        </div>
        <br>

        @if(auth()->user()->id == $thread->user_id)

        <div class="actions">
            <a href="{{route('thread.edit',$thread->id)}}" class="btn btn-info btn-xs">Edit</a>

            <form class="inline-it" action="{{route('thread.destroy',$thread->id)}}" method="POST">
                {{csrf_field()}}
                {{method_field('DELETE')}}
                <input class="btn btn-xs btn-danger" type="submit" value="Delete">
            </form>
        </div>
        @endif
    </div>
    <hr>
    <br>

    {{--Answer/Reply--}}

        @foreach($thread->comments as $comment)
            <div class="comment-list well well-lg">
                @include('thread.partials.comment-list')
            </div>
            <hr>

                {{--Reply to comment--}}
            <button class="btn btn-xs btn-default" onclick="toggleReply('{{$comment->id}}')">Reply</button>
            <br>
            {{--reply form--}}
            <div class="reply-form-{{$comment->id}} hidden" style="margin-left: 50px">
                <form action="{{route('replycomment.store',$comment->id)}}" method="post" role="form">
                    {{csrf_field()}}
                    <legend>Create Reply</legend>

                    <div class="form-group">
                        <input type="text" class="form-control" name="body" id="" placeholder="Type your reply here...">
                    </div>

                    <button type="submit" class="btn btn-primary">Reply</button>
                </form>
            </div>
            <br>

                @foreach($comment->comments as $reply)

                    @include('thread.partials.reply-list')

                @endforeach


        @endforeach


    <br><br>
        @include('thread.partials.comment-form')
    <br><br>
@endsection

@section('js')

    <script>
        function toggleReply(commentId){
            $('.reply-form-'+commentId).toggleClass('hidden');
        }
    </script>

@endsection